version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=gmedia_democase
      - DB_PORT=3306
    volumes:
      - .:/app
    restart: always
