CREATE TABLE IF NOT EXISTS admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password LONGTEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_token (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100),
  token TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS karyawan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nip VARCHAR(20) UNIQUE NOT NULL,
  nama VARCHAR(100) NOT NULL,
  alamat TEXT,
  gender ENUM('L', 'P') NOT NULL,
  tgl_lahir DATE NOT NULL,
  photo LONGTEXT,
  status INT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS log_trx_api (
  id INT AUTO_INCREMENT PRIMARY KEY,
  endpoint VARCHAR(255),
  nip VARCHAR(20),
  success TINYINT(1),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);